### PR TITLE
fix deadlock during prevote migration process

### LINKED ISSUE #20: raft: fix deadlock during PreVote migration process
refer https://github.com/coreos/etcd/pull/8525

### PR DESCRIPTION
**Pull request by csmoe**
Fixes #20

### CODE REVIEW

File: tests/cases/test_raft.rs [hunk 1]
```diff
@@ -3833,3 +3833,216 @@ fn test_remove_learner() {
...
+    ]);
+
+    nt.send(vec![new_message(3, 3, MessageType::MsgHup, 0)]);
+    nt.send(vec![new_message(3, 3, MessageType::MsgHup, 0)]);
+
+    // check state
+    // n1.state == Leader
+    // n2.state == Follower
+    // n3.state == Candidate
+    if nt.peers[&1].state != StateRole::Leader {
```
Comment (siddontang) [inline tests/cases/test_raft.rs]: you can use assert_eq here

File: tests/cases/test_raft.rs [hunk 2]
```diff
@@ -3833,3 +3833,216 @@ fn test_remove_learner() {
...
+            nt.peers[&3].state,
+            StateRole::Candidate
+        );
+    }
+
+    // check term
+    // n1.Term == 2
+    // n2.Term == 2
+    // n3.Term == 4
+    if nt.peers[&1].term != 2 {
```
Comment (siddontang) [inline tests/cases/test_raft.rs]: ditto

File: tests/cases/test_raft.rs [hunk 3]
```diff
@@ -3833,3 +3833,216 @@ fn test_remove_learner() {
...
+
+#[test]
+fn test_prevote_migration_can_complete_election() {
+    let mut nt = new_prevote_migration_cluster();
+
+    // n1 is leader with term 2
+    // n2 is follower with term 2
+    // n3 is pre-candidate with term 4, and less log
+
+	// simulate leader down
```
Comment (siddontang) [inline tests/cases/test_raft.rs]: please format your code with rustfmt nightly version 0.3.4

File: tests/cases/test_raft.rs [hunk 4]
```diff
@@ -3833,3 +3833,189 @@ fn test_remove_learner() {
...
+fn new_prevote_migration_cluster() -> Network {
+    let mut n1 = new_test_raft(1, vec![1, 2, 3], 10, 1, new_storage());
+    let mut n2 = new_test_raft(2, vec![1, 2, 3], 10, 1, new_storage());
+    let mut n3 = new_test_raft(3, vec![1, 2, 3], 10, 1, new_storage());
+
+    n1.become_follower(1, INVALID_ID);
+    n2.become_follower(1, INVALID_ID);
+    n3.become_follower(1, INVALID_ID);
+
+    // We intentionally do not enable pre_vote for n3, this is done so in order
```
Comment (BusyJay) [inline tests/cases/test_raft.rs]: The comment should be put to L3854.

File: tests/cases/test_raft.rs [hunk 5]
```diff
@@ -3833,3 +3833,189 @@ fn test_remove_learner() {
...
+    nt.peers.get_mut(&1).unwrap().pre_vote = true;
+
+    nt.send(vec![new_message(1, 1, MessageType::MsgHup, 0)]);
+
+    // Cause a network partition to isolate n3.
+    nt.isolate(3);
+    let mut e = Entry::new();
+    e.set_data(b"some data".to_vec());
+    nt.send(vec![
+          new_message_with_entries(1, 1, MessageType::MsgPropose, vec![e])
```
Comment (BusyJay) [inline tests/cases/test_raft.rs]: You can use `new_message(1, 1, MessageType::MsgPropose, 1)`.

File: tests/cases/test_raft.rs [hunk 6]
```diff
@@ -3833,3 +3833,189 @@ fn test_remove_learner() {
...
+
+    nt.send(vec![new_message(3, 3, MessageType::MsgHup, 0)]);
+    nt.send(vec![new_message(3, 3, MessageType::MsgHup, 0)]);
+
+    // check state
+    // n1.state == Leader
+    // n2.state == Follower
+    // n3.state == Candidate
+    assert_eq!(nt.peers[&1].state,
+               StateRole::Leader, "node 1 state: {:?}, want {:?}",
```
Comment (BusyJay) [inline tests/cases/test_raft.rs]: You don't have to customize the message as `assert_eq` did it for you already.

File: tests/cases/test_raft.rs [hunk 7]
```diff
@@ -3833,3 +3833,189 @@ fn test_remove_learner() {
...
+    n1.become_follower(1, INVALID_ID);
+    n2.become_follower(1, INVALID_ID);
+    n3.become_follower(1, INVALID_ID);
+
+    // We intentionally do not enable pre_vote for n3, this is done so in order
+    // to simulate a rolling restart process where it's possible to have a mixed
+    // version cluster with replicas with pre_vote enabled, and replicas without.
+    let mut nt = Network::new(vec![Some(n1), Some(n2), Some(n3)]);
+
+    nt.peers.get_mut(&2).unwrap().pre_vote = true;
```
Comment (BusyJay) [inline tests/cases/test_raft.rs]: You can use `new_test_raft_with_pre_vote`.

File: tests/cases/test_raft.rs [hunk 8]
```diff
@@ -3833,3 +3833,189 @@ fn test_remove_learner() {
...
+    nt.recover();
+
+    nt
+}
+
+#[test]
+fn test_prevote_migration_can_complete_election() {
+    let mut nt = new_prevote_migration_cluster();
+
+    // n1 is leader with term 2
```
Comment (BusyJay) [inline tests/cases/test_raft.rs]: Put the comment to L3923.

File: tests/cases/test_raft.rs [hunk 9]
```diff
@@ -3833,3 +3833,189 @@ fn test_remove_learner() {
...
+               nt.peers[&3].state,
+               StateRole::PreCandidate
+    );
+
+    nt.send(vec![new_message(3, 3, MessageType::MsgHup, 0)]);
+    nt.send(vec![new_message(2, 2, MessageType::MsgHup, 0)]);
+
+    // Do we have a leader?
+    // assert_eq!(nt.peers[&2].state, StateRole::Leader )
+    if nt.peers[&2].state != StateRole::Leader && nt.peers[&3].state != StateRole::Follower {
```
Comment (BusyJay) [inline tests/cases/test_raft.rs]: Use `assert!` instead.

File: src/raft.rs [hunk 10]
```diff
@@ -955,6 +955,27 @@ impl<T: Storage> Raft<T> {
                 // will not create disruptive term increases
                 let to_send = new_message(m.get_from(), MessageType::MsgAppendResponse, None);
                 self.send(to_send);
+            } else if m.get_msg_type() == MessageType::MsgRequestPreVote {
+                // Before pre_vote enable, there may have candidate with higher term,
```
Comment (BusyJay) [inline src/raft.rs]: The comment is confusing. I thought `candidate` here refers to the one who sends prevote request. Turns out it refers to the receiver. Could you make it better?

**Comment by Hoverbear** [comment]
Hi @csmoe, would you like any help with getting this PR merged? I see @BusyJay left a few comments. If you're busy I can wrap things up for you.

**Comment by csmoe** [comment]
@Hoverbear sorry for a delayed commit, I totally forgot this thread.
Feel free to do anything, thank you.

File: src/raft.rs [hunk 11]
```diff
@@ -955,6 +955,27 @@ impl<T: Storage> Raft<T> {
                 // will not create disruptive term increases
                 let to_send = new_message(m.get_from(), MessageType::MsgAppendResponse, None);
```
[the remark this answers is not in the document]
Comment (Hoverbear) [reply src/raft.rs]: Can you clarify what you'd like to see?

[the remark this answers is not in the document]
Comment (siddontang) [reply src/raft.rs]: maybe need to copy from etcd?

**Comment by Hoverbear** [comment]
@BusyJay Can you give this another look regarding the feedback you gave?

**Comment by siddontang** [comment]
PTAL @hicqu

File: tests/cases/test_raft.rs [hunk 12]
```diff
@@ -3978,3 +3978,154 @@ fn test_remove_learner() {
...
+               StateRole::PreCandidate, "node 3 state: {:?}, want {:?}",
+               nt.peers[&3].state,
+               StateRole::PreCandidate
+    );
+
+    nt.send(vec![new_message(3, 3, MessageType::MsgHup, 0)]);
+    nt.send(vec![new_message(2, 2, MessageType::MsgHup, 0)]);
+
+    // Do we have a leader?
+    assert_eq!(nt.peers[&2].state, StateRole::Leader);
```
Comment (siddontang) [inline tests/cases/test_raft.rs]: can we guarantee the leader can always be elected? It is different from https://github.com/coreos/etcd/pull/8525/files#diff-ad12a9c9b66e1507ca04edc74b4b1e8aR3386

**Comment by siddontang** [comment]
Rest LGTM

File: tests/cases/test_raft.rs [hunk 13]
```diff
@@ -3978,3 +3978,153 @@ fn test_remove_learner() {
...
+               StateRole::PreCandidate, "node 3 state: {:?}, want {:?}",
+               nt.peers[&3].state,
+               StateRole::PreCandidate
+    );
+
+    nt.send(vec![new_message(3, 3, MessageType::MsgHup, 0)]);
+    nt.send(vec![new_message(2, 2, MessageType::MsgHup, 0)]);
+
+    // Do we have a leader?
+    assert_eq!((nt.peers[&2].state, nt.peers[&3].state), (StateRole::Leader, StateRole::Follower));
```
Comment (siddontang) [inline tests/cases/test_raft.rs]: I think this is still different from https://github.com/coreos/etcd/pull/8525/files?utf8=%E2%9C%93&diff=unified#diff-ad12a9c9b66e1507ca04edc74b4b1e8aR3386.

Comment (csmoe) [reply tests/cases/test_raft.rs]: sorry, I don't know how to fix this since I thought this tuple comparsion might work like `&&`. could you give me some tips?
Will simulating leader down(`nt.solate(1)`) before new election guarantee that?

Comment (siddontang) [reply tests/cases/test_raft.rs]: in your test, you require 2 must be the leader, and 3 must be the follower. But in the etcd test, if 2 is the leader, 3 can be not the follower.

Comment (csmoe) [reply tests/cases/test_raft.rs]: oh, thank you, I have made a logic mistake here.

File: src/raft.rs [hunk 14]
```diff
@@ -224,7 +224,7 @@ pub struct Raft<T: Storage> {
     heartbeat_elapsed: usize,
 
     pub check_quorum: bool,
-    pre_vote: bool,
+    pub pre_vote: bool,
```
Comment (BusyJay) [inline src/raft.rs]: Please add a doc hidden attribute.

File: tests/cases/test_raft.rs [hunk 15]
```diff
@@ -3978,3 +3978,156 @@ fn test_remove_learner() {
...
+    // n1 is leader with term 2
+    // n2 is follower with term 2
+    // n3 is pre-candidate with term 4, and less log
+    let mut nt = new_prevote_migration_cluster();
+
+    // simulate leader down
+    nt.isolate(1);
+
+    // Call for elections from both n2 and n3.
+    nt.send(vec![new_message(2, 2, MessageType::MsgHup, 0)]);
```
Comment (BusyJay) [inline tests/cases/test_raft.rs]: Order is important, although it won't affect the test result (yet).

File: tests/cases/test_raft.rs [hunk 16]
```diff
@@ -3978,3 +3978,156 @@ fn test_remove_learner() {
...
+fn test_prevote_migration_with_free_stuck_pre_candidate() {
+    let mut nt = new_prevote_migration_cluster();
+
+    // n1 is leader with term 2
+    // n2 is follower with term 2
+    // n3 is pre-candidate with term 4, and less log
+    nt.send(vec![new_message(3, 3, MessageType::MsgHup, 0)]);
+
+    assert_eq!(nt.peers[&1].state,
+               StateRole::Leader, "node 1 state: {:?}, want {:?}",
```
Comment (BusyJay) [inline tests/cases/test_raft.rs]: Debug message is unnecessary.

**Comment by siddontang** [comment]
PTAL @Hoverbear

**Comment by Hoverbear** [comment]
Please run `cargo fmt` and we can merge this. :) We just merged #55 which runs code on the CI through `rustfmt`.

**Comment by csmoe** [comment]
@Hoverbear The current rustfmt in CI is stable-ver, but:
```
Warning: can't set `use_try_shorthand = true`, unstable features are only available in nightly channel.
```
So rustfmt config might need changes.

**Comment by siddontang** [comment]
Ping @Hoverbear

**Comment by Hoverbear** [comment]
Opened https://github.com/pingcap/raft-rs/issues/62 to reflect the `cargo fmt` warnings.
