### PR TITLE
Check pending conf change before campaign

### LINKED ISSUE #221: Votes should be updated when doing conf change
If conf change remove a node, its vote should also be removed. Otherwise we can get the wrong number of agree votes and lead to an election failure.

### PR DESCRIPTION
**Pull request by BusyJay**
Fix #221.

This is a fix for 0.4.x, I will do the fix for master later.

### CODE REVIEW

**Comment by siddontang** [comment]
@nolouch 

I think we should contribute to etcd later.

**Comment by siddontang** [comment]
PTAL @xiang90

File: tests/integration_cases/test_raft.rs [hunk 1]
```diff
@@ -4049,3 +4049,65 @@ fn test_prevote_with_check_quorum() {
     assert_eq!(network.peers[&2].state, StateRole::Leader, "peer 2 state",);
     assert_eq!(network.peers[&3].state, StateRole::Follower, "peer 3 state",);
 }
+
+/// Tests if unapplied conf change is checked before campaign.
+#[test]
+fn test_conf_change_check_before_campaign() {
```
Comment (siddontang) [inline tests/integration_cases/test_raft.rs]: if we don't call `self.hub(true)`, the test can fail?

Comment (BusyJay) [reply tests/integration_cases/test_raft.rs]: Yes. The case was written before the fix, and it failed.

**Comment by BusyJay** [comment]
Seems criterion's API is broken. @Hoverbear Would you like to take a look?

**Comment by siddontang** [comment]
@BusyJay 

seem some failed tests were not caused by criterion API changes.

**Comment by BusyJay** [comment]
@siddontang can you name some? I can't find them.

**Comment by siddontang** [comment]
```
thread 'raft_log::test::test_commit_to' panicked at ' to_commit 4 is out of range [last_index 3]', src/raft_log.rs:248:13
test raft_log::test::test_append ... ok
thread 'raft_log::test::test_compaction' panicked at 'compact 1001 is out of bound lastindex(1000)', src/storage.rs:174:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:340
   7: <raft::raft_log::RaftLog<T>>::commit_to
             at src/raft_log.rs:248
   8: raft::raft_log::test::test_commit_to::{{closure}}
             at src/raft_log.rs:1285
   9: core::ops::function::FnOnce::call_once
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/ops/function.rs:231
  10: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/panic.rs:309
  11: std::panicking::try::do_call
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/panicking.rs:297
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  13: std::panicking::try
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/panicking.rs:276
  14: std::panic::catch_unwind
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/panic.rs:388
  15: raft::raft_log::test::test_commit_to
             at src/raft_log.rs:1285
  16: raft::raft_log::test::test_commit_to::{{closure}}
             at src/raft_log.rs:1270
  17: core::ops::function::FnOnce::call_once
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/ops/function.rs:231
  18: <F as alloc::boxed::FnBox<A>>::call_box
             at src/libtest/lib.rs:1497
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libcore/ops/function.rs:231
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/liballoc/boxed.rs:749
  19: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  20: test::run_test::run_test_inner::{{closure}}
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/panicking.rs:276
             at /rustc/fc50f328b0353b285421b8ff5d4100966387a997/src/libstd/panic.rs:388
             at src/libtest/lib.rs:1452
```

**Comment by BusyJay** [comment]
Those tests are expected to panic. They are wrapped with UnwindSafe.

File: src/raft.rs [hunk 2]
```diff
@@ -1079,6 +1048,55 @@ impl<T: Storage> Raft<T> {
...
+                panic!(
+                    "{} unexpected error getting unapplied entries [{}, {}): {:?}",
+                    self.tag,
+                    first_index,
+                    self.raft_log.committed + 1,
+                    e
+                );
+            });
+        let n = self.num_pending_conf(&ents);
+        if n != 0 && self.raft_log.committed > self.raft_log.applied {
```
Comment (hicqu) [inline src/raft.rs]: Why not use `pending_conf_index` directly?

Comment (hicqu) [inline src/raft.rs]: I think `n != 0` also means `committed > applied`.

Comment (hicqu) [reply src/raft.rs]: In this case I think `raft_log.applied` must be less than `snapshot.index`, so I think only `n != 0` is ok here.

Comment (BusyJay) [reply src/raft.rs]: `raft_log.applied` can be any value less than the snapshot index.

**Comment by hicqu** [comment]
LGTM.
