### PR TITLE
Use stable Rust.

### LINKED ISSUE #8: Use Stable Rust
As part of #1 we'd like to use Stable Rust.

Currently the only feature we use is:

https://github.com/pingcap/raft-rs/blob/1badec3bfa0c8f25da196050d1ba015c9efc5d4a/src/lib.rs#L32

Disabling this yields:

```
error: `impl Trait` in return position is experimental (see issue #34511)
  --> src/progress.rs:91:34
   |
91 |     pub fn iter<'a>(&'a self) -> impl Iterator<Item = (&'a u64, &'a Progress)> {
   |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(conservative_impl_trait)] to the crate attributes to enable

error: `impl Trait` in return position is experimental (see issue #34511)
  --> src/progress.rs:96:42
   |
96 |     pub fn iter_mut<'a>(&'a mut self) -> impl Iterator<Item = (&'a u64, &'a mut Progress)> {
   |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(conservative_impl_trait)] to the crate attributes to enable
```

In order to stabilize we need to change these.

### PR DESCRIPTION
**Pull request by Hoverbear**
Migrates us to stable Rust by removing the `conservative_impl_trait`
feature.

Please note you still need to use `nightly` for `cargo test --features "dev"` since we use `clippy`.

Fixes #8. Contributes to #1.

### CODE REVIEW

File: src/progress.rs [hunk 1]
```diff
@@ -88,12 +90,12 @@ impl ProgressSet {
     // We need explicit lifetime here because of a compiler bug.
     // See https://github.com/rust-lang/rust/issues/43396.
     #[allow(needless_lifetimes)]
-    pub fn iter<'a>(&'a self) -> impl Iterator<Item = (&'a u64, &'a Progress)> {
+    pub fn iter<'a>(&'a self) -> Chain<flat_map::Iter<u64, Progress>, flat_map::Iter<'a, u64, Progress>> {
```
Comment (BusyJay) [inline src/progress.rs]: Lifetime can be removed now.

**Comment by Hoverbear** [comment]
`cargo test` now runs on `stable`, however in order to use `cargo test --features "dev"` `nightly` is still needed.

File: src/progress.rs [hunk 2]
```diff
@@ -87,13 +89,11 @@ impl ProgressSet {
 
     // We need explicit lifetime here because of a compiler bug.
     // See https://github.com/rust-lang/rust/issues/43396.
-    #[allow(needless_lifetimes)]
-    pub fn iter<'a>(&'a self) -> impl Iterator<Item = (&'a u64, &'a Progress)> {
+    pub fn iter(&self) -> Chain<flat_map::Iter<u64, Progress>, flat_map::Iter<u64, Progress>> {
```
Comment (BusyJay) [inline src/progress.rs]: Please update the comment too.

Comment (Hoverbear) [reply src/progress.rs]: Ah, great catch, thanks!
